import { Migration } from "@mikro-orm/migrations";

export class Migration20260927180400_initial extends Migration {
  override name = "Migration20260927180400_initial";

  override up(): void {
    this.addSql("create table `verification` (`id` varchar(255) not null, `identifier` varchar(255) not null, `value` text not null, `expires_at` datetime not null, `created_at` datetime null, `updated_at` datetime null, primary key (`id`)) default character set utf8mb4 engine = InnoDB;");
    this.addSql("alter table `verification` add index `verification_identifier_index` (`identifier`);");
    this.addSql("create table `core_event` (`id` varchar(255) not null, `title` varchar(255) not null, `start_time` datetime not null, `end_time` datetime not null, `location` varchar(255) not null default 'TBD', `description` text not null, `type` varchar(255) not null, `host` varchar(255) null, `hidden` tinyint(1) not null default false, `created_at` datetime not null, `updated_at` datetime not null, primary key (`id`)) default character set utf8mb4 engine = InnoDB;");
    this.addSql("alter table `core_event` add index `core_event_start_time_index` (`start_time`);");
    this.addSql("alter table `core_event` add index `core_event_type_index` (`type`);");
    this.addSql("alter table `core_event` add index `core_event_hidden_index` (`hidden`);");
    this.addSql("create table `core_operation_lock` (`key` varchar(255) not null, `token` varchar(255) not null, primary key (`key`)) default character set utf8mb4 engine = InnoDB;");
    this.addSql("create table `core_role` (`id` varchar(255) not null, `name` varchar(255) not null, `position` int not null, `permissions` json not null default ('[]'), `color` varchar(255) null, `created_at` datetime not null, `updated_at` datetime not null, primary key (`id`)) default character set utf8mb4 engine = InnoDB;");
    this.addSql("alter table `core_role` add unique `core_role_name_unique` (`name`);");
    this.addSql("alter table `core_role` add index `core_role_position_index` (`position`);");
    this.addSql("create table `core_user` (`id` varchar(255) not null, `name` varchar(255) not null, `email` varchar(255) not null, `email_verified` tinyint(1) not null default false, `profile_photo_url` text null, `hack_tag` varchar(255) null, `bio` text null, `pronouns` varchar(255) null, `skills` json not null default ('[]'), `is_profile_searchable` tinyint(1) not null default true, `discord_display_handle` varchar(255) null, `role_id` varchar(255) null, `is_approved` tinyint(1) not null default false, `checked_in_at` datetime null, `created_at` datetime not null, `updated_at` datetime not null, primary key (`id`)) default character set utf8mb4 engine = InnoDB;");
    this.addSql("alter table `core_user` add unique `core_user_email_unique` (`email`);");
    this.addSql("alter table `core_user` add unique `core_user_hack_tag_unique` (`hack_tag`);");
    this.addSql("alter table `core_user` add index `core_user_hack_tag_index` (`hack_tag`);");
    this.addSql("alter table `core_user` add index `core_user_role_id_index` (`role_id`);");
    this.addSql("alter table `core_user` add index `core_user_created_at_index` (`created_at`);");
    this.addSql("create table `discord_verification` (`code` varchar(255) not null, `discord_user_id` varchar(255) not null, `guild_id` varchar(255) not null, `username` varchar(255) not null, `avatar_hash` varchar(255) null, `auth_id` varchar(255) null, `status` enum('pending','accepted','rejected','expired') not null default 'pending', `expires_at` datetime not null, `created_at` datetime not null, `accepted_at` datetime null, primary key (`code`)) default character set utf8mb4 engine = InnoDB;");
    this.addSql("alter table `discord_verification` add index `discord_verification_discord_user_id_index` (`discord_user_id`);");
    this.addSql("alter table `discord_verification` add index `discord_verification_guild_id_index` (`guild_id`);");
    this.addSql("alter table `discord_verification` add index `discord_verification_auth_id_index` (`auth_id`);");
    this.addSql("alter table `discord_verification` add index `discord_verification_status_index` (`status`);");
    this.addSql("alter table `discord_verification` add index `discord_verification_created_at_index` (`created_at`);");
    this.addSql("create table `discord_role_sync_attempt` (`id` varchar(255) not null, `auth_id` varchar(255) not null, `discord_user_id` varchar(255) not null, `guild_id` varchar(255) not null, `status` enum('synced','failed','skipped') not null, `role_ids` json not null default ('[]'), `role_names` json not null default ('[]'), `error` text null, `created_at` datetime not null, primary key (`id`)) default character set utf8mb4 engine = InnoDB;");
    this.addSql("alter table `discord_role_sync_attempt` add index `discord_role_sync_attempt_auth_id_index` (`auth_id`);");
    this.addSql("alter table `discord_role_sync_attempt` add index `discord_role_sync_attempt_discord_user_id_index` (`discord_user_id`);");
    this.addSql("alter table `discord_role_sync_attempt` add index `discord_role_sync_attempt_status_index` (`status`);");
    this.addSql("alter table `discord_role_sync_attempt` add index `discord_role_sync_attempt_created_at_index` (`created_at`);");
    this.addSql("create table `discord_member` (`auth_id` varchar(255) not null, `discord_user_id` varchar(255) not null, `guild_id` varchar(255) not null, `username` varchar(255) not null, `avatar_hash` varchar(255) null, `verified_at` datetime not null, `updated_at` datetime not null, `last_role_sync_at` datetime null, primary key (`auth_id`)) default character set utf8mb4 engine = InnoDB;");
    this.addSql("alter table `discord_member` add index `discord_member_auth_id_index` (`auth_id`);");
    this.addSql("alter table `discord_member` add unique `discord_member_discord_user_id_unique` (`discord_user_id`);");
    this.addSql("alter table `discord_member` add index `discord_member_discord_user_id_index` (`discord_user_id`);");
    this.addSql("alter table `discord_member` add index `discord_member_guild_id_index` (`guild_id`);");
    this.addSql("alter table `discord_member` add index `discord_member_updated_at_index` (`updated_at`);");
    this.addSql("create table `core_user_data` (`auth_id` varchar(255) not null, `age` int not null, `gender` varchar(255) not null, `race` varchar(255) not null, `ethnicity` varchar(255) not null, `shirt_size` varchar(255) not null, `dietary_restrictions` json not null default ('[]'), `accommodation_note` text null, `phone_number` varchar(255) null, `country_of_residence` varchar(255) null, `has_accepted_mlhcode_of_conduct` tinyint(1) not null, `has_shared_data_with_mlh` tinyint(1) not null, `is_emailable` tinyint(1) not null, `completed_at` datetime not null, `updated_at` datetime not null, primary key (`auth_id`)) default character set utf8mb4 engine = InnoDB;");
    this.addSql("alter table `core_user_data` add index `core_user_data_auth_id_index` (`auth_id`);");
    this.addSql("create table `core_user_ban` (`auth_id` varchar(255) not null, `reason` varchar(255) null, `banned_by_auth_id` varchar(255) not null, `created_at` datetime not null, primary key (`auth_id`)) default character set utf8mb4 engine = InnoDB;");
    this.addSql("alter table `core_user_ban` add index `core_user_ban_auth_id_index` (`auth_id`);");
    this.addSql("alter table `core_user_ban` add index `core_user_ban_banned_by_auth_id_index` (`banned_by_auth_id`);");
    this.addSql("create table `core_setting` (`key` varchar(255) not null, `value` json not null, `created_at` datetime not null, `created_by_auth_id` varchar(255) null, `updated_at` datetime not null, `updated_by_auth_id` varchar(255) null, primary key (`key`)) default character set utf8mb4 engine = InnoDB;");
    this.addSql("alter table `core_setting` add index `core_setting_created_by_auth_id_index` (`created_by_auth_id`);");
    this.addSql("alter table `core_setting` add index `core_setting_updated_at_index` (`updated_at`);");
    this.addSql("alter table `core_setting` add index `core_setting_updated_by_auth_id_index` (`updated_by_auth_id`);");
    this.addSql("create table `core_rsvp` (`auth_id` varchar(255) not null, `status` enum('confirmed','waitlisted','cancelled') not null, `waitlist_position` int null, `created_at` datetime not null, `updated_at` datetime not null, `confirmed_at` datetime null, `waitlisted_at` datetime null, `cancelled_at` datetime null, `cancelled_by_auth_id` varchar(255) null, `promoted_at` datetime null, `promoted_by_auth_id` varchar(255) null, primary key (`auth_id`)) default character set utf8mb4 engine = InnoDB;");
    this.addSql("alter table `core_rsvp` add index `core_rsvp_auth_id_index` (`auth_id`);");
    this.addSql("alter table `core_rsvp` add index `core_rsvp_cancelled_by_auth_id_index` (`cancelled_by_auth_id`);");
    this.addSql("alter table `core_rsvp` add index `core_rsvp_promoted_by_auth_id_index` (`promoted_by_auth_id`);");
    this.addSql("alter table `core_rsvp` add index `core_rsvp_status_index` (`status`);");
    this.addSql("alter table `core_rsvp` add index `core_rsvp_waitlist_position_index` (`waitlist_position`);");
    this.addSql("alter table `core_rsvp` add index `core_rsvp_created_at_index` (`created_at`);");
    this.addSql("alter table `core_rsvp` add index `core_rsvp_updated_at_index` (`updated_at`);");
    this.addSql("create table `core_notification_intent` (`id` varchar(255) not null, `kind` varchar(255) not null, `recipient_auth_id` varchar(255) null, `payload` json not null, `status` enum('pending','processing','delivered','failed','skipped') not null default 'pending', `idempotency_key` varchar(255) null, `created_at` datetime not null, `updated_at` datetime not null, primary key (`id`)) default character set utf8mb4 engine = InnoDB;");
    this.addSql("alter table `core_notification_intent` add unique `core_notification_intent_idempotency_key_unique` (`idempotency_key`);");
    this.addSql("alter table `core_notification_intent` add index `core_notification_intent_kind_index` (`kind`);");
    this.addSql("alter table `core_notification_intent` add index `core_notification_intent_recipient_auth_id_index` (`recipient_auth_id`);");
    this.addSql("alter table `core_notification_intent` add index `core_notification_intent_status_index` (`status`);");
    this.addSql("alter table `core_notification_intent` add index `core_notification_intent_created_at_index` (`created_at`);");
    this.addSql("create table `core_notification_delivery_attempt` (`id` varchar(255) not null, `intent_id` varchar(255) not null, `channel` varchar(255) not null, `provider` varchar(255) null, `status` enum('delivered','failed','skipped') not null, `recipient` varchar(255) null, `external_id` varchar(255) null, `error` text null, `metadata` json not null, `attempted_at` datetime not null, primary key (`id`)) default character set utf8mb4 engine = InnoDB;");
    this.addSql("alter table `core_notification_delivery_attempt` add index `core_notification_delivery_attempt_intent_id_index` (`intent_id`);");
    this.addSql("alter table `core_notification_delivery_attempt` add index `core_notification_delivery_attempt_channel_index` (`channel`);");
    this.addSql("alter table `core_notification_delivery_attempt` add index `core_notification_delivery_attempt_status_index` (`status`);");
    this.addSql("alter table `core_notification_delivery_attempt` add index `core_notification_delivery_attempt_attempted_at_index` (`attempted_at`);");
    this.addSql("create table `core_hacker` (`auth_id` varchar(255) not null, `university` varchar(255) not null, `major` varchar(255) not null, `school_id` varchar(255) null, `level_of_study` varchar(255) not null, `hackathons_attended` int not null, `software_experience` varchar(255) not null, `heard_from` varchar(255) null, `github_url` text null, `linked_in_url` text null, `personal_website_url` text null, `resume_url` text null, `group` varchar(255) null, `registered_at` datetime not null, `updated_at` datetime not null, primary key (`auth_id`)) default character set utf8mb4 engine = InnoDB;");
    this.addSql("alter table `core_hacker` add index `core_hacker_auth_id_index` (`auth_id`);");
    this.addSql("alter table `core_hacker` add index `core_hacker_registered_at_index` (`registered_at`);");
    this.addSql("create table `core_event_scan` (`id` varchar(255) not null, `event_id` varchar(255) not null, `auth_id` varchar(255) not null, `scanned_by_auth_id` varchar(255) not null, `scanned_at` datetime not null, primary key (`id`)) default character set utf8mb4 engine = InnoDB;");
    this.addSql("alter table `core_event_scan` add index `core_event_scan_scanned_by_auth_id_index` (`scanned_by_auth_id`);");
    this.addSql("alter table `core_event_scan` add index `core_event_scan_event_id_index` (`event_id`);");
    this.addSql("alter table `core_event_scan` add index `core_event_scan_auth_id_index` (`auth_id`);");
    this.addSql("alter table `core_event_scan` add index `core_event_scan_event_id_auth_id_index` (`event_id`, `auth_id`);");
    this.addSql("alter table `core_event_scan` add index `core_event_scan_scanned_at_index` (`scanned_at`);");
    this.addSql("create table `session` (`id` varchar(255) not null, `expires_at` datetime not null, `token` varchar(255) not null, `created_at` datetime not null, `updated_at` datetime not null, `ip_address` varchar(255) null, `user_agent` text null, `user_id` varchar(255) not null, primary key (`id`)) default character set utf8mb4 engine = InnoDB;");
    this.addSql("alter table `session` add unique `session_token_unique` (`token`);");
    this.addSql("alter table `session` add index `session_user_id_index` (`user_id`);");
    this.addSql("create table `account` (`id` varchar(255) not null, `account_id` varchar(255) not null, `provider_id` varchar(255) not null, `user_id` varchar(255) not null, `access_token` text null, `refresh_token` text null, `id_token` text null, `access_token_expires_at` datetime null, `refresh_token_expires_at` datetime null, `scope` text null, `password` varchar(255) null, `created_at` datetime not null, `updated_at` datetime not null, primary key (`id`)) default character set utf8mb4 engine = InnoDB;");
    this.addSql("alter table `account` add index `account_user_id_index` (`user_id`);");
    this.addSql("create table `teams_team` (`id` varchar(255) not null, `name` varchar(255) not null, `tag` varchar(255) not null, `owner_auth_id` varchar(255) not null, `created_at` datetime not null, primary key (`id`)) default character set utf8mb4 engine = InnoDB;");
    this.addSql("alter table `teams_team` add unique `teams_team_tag_unique` (`tag`);");
    this.addSql("alter table `teams_team` add index `teams_team_tag_index` (`tag`);");
    this.addSql("alter table `teams_team` add index `teams_team_owner_auth_id_index` (`owner_auth_id`);");
    this.addSql("create table `teams_member` (`id` varchar(255) not null, `team_id` varchar(255) not null, `auth_id` varchar(255) not null, `joined_at` datetime not null, primary key (`id`)) default character set utf8mb4 engine = InnoDB;");
    this.addSql("alter table `teams_member` add unique `teams_member_auth_id_unique` (`auth_id`);");
    this.addSql("alter table `teams_member` add index `teams_member_team_id_index` (`team_id`);");
    this.addSql("alter table `teams_member` add index `teams_member_auth_id_index` (`auth_id`);");
    this.addSql("create table `teams_invite` (`id` varchar(255) not null, `team_id` varchar(255) not null, `invitee_auth_id` varchar(255) not null, `status` enum('pending','accepted','declined') not null default 'pending', `created_at` datetime not null, primary key (`id`)) default character set utf8mb4 engine = InnoDB;");
    this.addSql("alter table `teams_invite` add index `teams_invite_team_id_index` (`team_id`);");
    this.addSql("alter table `teams_invite` add index `teams_invite_invitee_auth_id_index` (`invitee_auth_id`);");
    this.addSql("alter table `teams_invite` add index `teams_invite_team_id_invitee_auth_id_index` (`team_id`, `invitee_auth_id`);");
    this.addSql("alter table `core_user` add constraint `core_user_role_id_foreign` foreign key (`role_id`) references `core_role` (`id`) on delete set null;");
    this.addSql("alter table `discord_verification` add constraint `discord_verification_auth_id_foreign` foreign key (`auth_id`) references `core_user` (`id`) on delete set null;");
    this.addSql("alter table `discord_role_sync_attempt` add constraint `discord_role_sync_attempt_auth_id_foreign` foreign key (`auth_id`) references `core_user` (`id`) on delete cascade;");
    this.addSql("alter table `discord_member` add constraint `discord_member_auth_id_foreign` foreign key (`auth_id`) references `core_user` (`id`) on update cascade on delete cascade;");
    this.addSql("alter table `core_user_data` add constraint `core_user_data_auth_id_foreign` foreign key (`auth_id`) references `core_user` (`id`) on update cascade on delete cascade;");
    this.addSql("alter table `core_user_ban` add constraint `core_user_ban_auth_id_foreign` foreign key (`auth_id`) references `core_user` (`id`) on update cascade on delete cascade;");
    this.addSql("alter table `core_user_ban` add constraint `core_user_ban_banned_by_auth_id_foreign` foreign key (`banned_by_auth_id`) references `core_user` (`id`);");
    this.addSql("alter table `core_setting` add constraint `core_setting_created_by_auth_id_foreign` foreign key (`created_by_auth_id`) references `core_user` (`id`) on delete set null;");
    this.addSql("alter table `core_setting` add constraint `core_setting_updated_by_auth_id_foreign` foreign key (`updated_by_auth_id`) references `core_user` (`id`) on delete set null;");
    this.addSql("alter table `core_rsvp` add constraint `core_rsvp_auth_id_foreign` foreign key (`auth_id`) references `core_user` (`id`) on update cascade on delete cascade;");
    this.addSql("alter table `core_rsvp` add constraint `core_rsvp_cancelled_by_auth_id_foreign` foreign key (`cancelled_by_auth_id`) references `core_user` (`id`) on delete set null;");
    this.addSql("alter table `core_rsvp` add constraint `core_rsvp_promoted_by_auth_id_foreign` foreign key (`promoted_by_auth_id`) references `core_user` (`id`) on delete set null;");
    this.addSql("alter table `core_notification_intent` add constraint `core_notification_intent_recipient_auth_id_foreign` foreign key (`recipient_auth_id`) references `core_user` (`id`) on delete set null;");
    this.addSql("alter table `core_notification_delivery_attempt` add constraint `core_notification_delivery_attempt_intent_id_foreign` foreign key (`intent_id`) references `core_notification_intent` (`id`) on delete cascade;");
    this.addSql("alter table `core_hacker` add constraint `core_hacker_auth_id_foreign` foreign key (`auth_id`) references `core_user` (`id`) on update cascade on delete cascade;");
    this.addSql("alter table `core_event_scan` add constraint `core_event_scan_event_id_foreign` foreign key (`event_id`) references `core_event` (`id`) on delete cascade;");
    this.addSql("alter table `core_event_scan` add constraint `core_event_scan_auth_id_foreign` foreign key (`auth_id`) references `core_user` (`id`) on delete cascade;");
    this.addSql("alter table `core_event_scan` add constraint `core_event_scan_scanned_by_auth_id_foreign` foreign key (`scanned_by_auth_id`) references `core_user` (`id`);");
    this.addSql("alter table `session` add constraint `session_user_id_foreign` foreign key (`user_id`) references `core_user` (`id`) on delete cascade;");
    this.addSql("alter table `account` add constraint `account_user_id_foreign` foreign key (`user_id`) references `core_user` (`id`) on delete cascade;");
    this.addSql("alter table `teams_team` add constraint `teams_team_owner_auth_id_foreign` foreign key (`owner_auth_id`) references `core_user` (`id`) on delete cascade;");
    this.addSql("alter table `teams_member` add constraint `teams_member_team_id_foreign` foreign key (`team_id`) references `teams_team` (`id`) on delete cascade;");
    this.addSql("alter table `teams_member` add constraint `teams_member_auth_id_foreign` foreign key (`auth_id`) references `core_user` (`id`) on delete cascade;");
    this.addSql("alter table `teams_invite` add constraint `teams_invite_team_id_foreign` foreign key (`team_id`) references `teams_team` (`id`) on delete cascade;");
    this.addSql("alter table `teams_invite` add constraint `teams_invite_invitee_auth_id_foreign` foreign key (`invitee_auth_id`) references `core_user` (`id`) on delete cascade;");
  }

  override down(): void | Promise<void> {
    this.addSql(`alter table \`session\` drop foreign key \`session_user_id_foreign\`;`);
    this.addSql(`alter table \`account\` drop foreign key \`account_user_id_foreign\`;`);
    this.addSql(`alter table \`core_event_scan\` drop foreign key \`core_event_scan_event_id_foreign\`;`);
    this.addSql(`alter table \`core_user\` drop foreign key \`core_user_role_id_foreign\`;`);
    this.addSql(`alter table \`discord_verification\` drop foreign key \`discord_verification_auth_id_foreign\`;`);
    this.addSql(`alter table \`discord_role_sync_attempt\` drop foreign key \`discord_role_sync_attempt_auth_id_foreign\`;`);
    this.addSql(`alter table \`discord_member\` drop foreign key \`discord_member_auth_id_foreign\`;`);
    this.addSql(`alter table \`core_user_data\` drop foreign key \`core_user_data_auth_id_foreign\`;`);
    this.addSql(`alter table \`core_user_ban\` drop foreign key \`core_user_ban_auth_id_foreign\`;`);
    this.addSql(`alter table \`core_user_ban\` drop foreign key \`core_user_ban_banned_by_auth_id_foreign\`;`);
    this.addSql(`alter table \`core_setting\` drop foreign key \`core_setting_created_by_auth_id_foreign\`;`);
    this.addSql(`alter table \`core_setting\` drop foreign key \`core_setting_updated_by_auth_id_foreign\`;`);
    this.addSql(`alter table \`core_rsvp\` drop foreign key \`core_rsvp_auth_id_foreign\`;`);
    this.addSql(`alter table \`core_rsvp\` drop foreign key \`core_rsvp_cancelled_by_auth_id_foreign\`;`);
    this.addSql(`alter table \`core_rsvp\` drop foreign key \`core_rsvp_promoted_by_auth_id_foreign\`;`);
    this.addSql(`alter table \`core_notification_intent\` drop foreign key \`core_notification_intent_recipient_auth_id_foreign\`;`);
    this.addSql(`alter table \`core_hacker\` drop foreign key \`core_hacker_auth_id_foreign\`;`);
    this.addSql(`alter table \`core_event_scan\` drop foreign key \`core_event_scan_auth_id_foreign\`;`);
    this.addSql(`alter table \`core_event_scan\` drop foreign key \`core_event_scan_scanned_by_auth_id_foreign\`;`);
    this.addSql(`alter table \`teams_team\` drop foreign key \`teams_team_owner_auth_id_foreign\`;`);
    this.addSql(`alter table \`teams_member\` drop foreign key \`teams_member_auth_id_foreign\`;`);
    this.addSql(`alter table \`teams_invite\` drop foreign key \`teams_invite_invitee_auth_id_foreign\`;`);
    this.addSql(`alter table \`core_notification_delivery_attempt\` drop foreign key \`core_notification_delivery_attempt_intent_id_foreign\`;`);
    this.addSql(`alter table \`teams_member\` drop foreign key \`teams_member_team_id_foreign\`;`);
    this.addSql(`alter table \`teams_invite\` drop foreign key \`teams_invite_team_id_foreign\`;`);

    this.addSql(`drop table if exists \`session\`;`);
    this.addSql(`drop table if exists \`account\`;`);
    this.addSql(`drop table if exists \`verification\`;`);
    this.addSql(`drop table if exists \`core_event\`;`);
    this.addSql(`drop table if exists \`core_operation_lock\`;`);
    this.addSql(`drop table if exists \`core_role\`;`);
    this.addSql(`drop table if exists \`core_user\`;`);
    this.addSql(`drop table if exists \`discord_verification\`;`);
    this.addSql(`drop table if exists \`discord_role_sync_attempt\`;`);
    this.addSql(`drop table if exists \`discord_member\`;`);
    this.addSql(`drop table if exists \`core_user_data\`;`);
    this.addSql(`drop table if exists \`core_user_ban\`;`);
    this.addSql(`drop table if exists \`core_setting\`;`);
    this.addSql(`drop table if exists \`core_rsvp\`;`);
    this.addSql(`drop table if exists \`core_notification_intent\`;`);
    this.addSql(`drop table if exists \`core_notification_delivery_attempt\`;`);
    this.addSql(`drop table if exists \`core_hacker\`;`);
    this.addSql(`drop table if exists \`core_event_scan\`;`);
    this.addSql(`drop table if exists \`teams_team\`;`);
    this.addSql(`drop table if exists \`teams_member\`;`);
    this.addSql(`drop table if exists \`teams_invite\`;`);
  }

}
